export const propertySampleData = [
  {
    id: 0,
    title: "Rhoncus suspendisse penatibus mauris, sit non",
    image: "/images/Accommodation/room0.png",
    roomDetails:
      "1 bedroom | 1 bath | WiFi | City view | 3rd floor | Elevator | Parking",
    available: "28 Nov 2021",
    price: 3490,
    description:
      "A truly global city, London has long been considered a cutting-edge metropolis and hub for culture, style and finance. With each borough, Tube zone and neighborhood of London sporting its own vibe and lifestyle advantages, it can be downright difficult to settle on where to look for a furnished apartment in London . Whether you’re a digital nomad looking for a studio apartment in London or just seeking a month to month rental in London, Blueground has you covered.",
    summary: [
      "1 bedroom",
      "1 bath",
      "WiFi",
      "City view",
      "3rd floor",
      "Elevator",
      "Parking",
    ],
    galleryImages: [
      "/images/Accommodation/property1.1.jpg",
      "/images/Accommodation/property1.2.jpg",
    ],
    amenities: [
      { name: "TV", icon: "bi-tv", note: "Flatscreen TV" },
      { name: "Fireplace", icon: "bi-fire" },
      { name: "Phone", icon: "bi-telephone" },
      { name: "Work desk", icon: "bi-laptop", note: "With computer" },
      { name: "Fridge", icon: "bi-box" },
      { name: "Kettle", icon: "bi-cup" },
      { name: "Coffee machine", icon: "bi-cup-hot" },
      { name: "Dishes", icon: "bi-egg-fried" },
      { name: "Washing machine", icon: "bi-droplet" },
      { name: "Dryer", icon: "bi-wind" },
      { name: "Iron", icon: "bi-lightning-charge" },
      { name: "Wardrobe", icon: "bi-door-closed" },
    ],
    mapPosition: [51.505, -0.224],
  },
  {
    id: 1,
    title: "Rhoncus suspendisse penatibus mauris, sit non",
    image: "/images/Accommodation/room1.png",
    roomDetails:
      "1 bedroom | 1 bath | WiFi | City view | 3rd floor | Elevator | Parking",
    available: "28 Nov 2021",
    price: 3490,
    description:
      "A truly global city, London has long been considered a cutting-edge metropolis and hub for culture, style and finance. With each borough, Tube zone and neighborhood of London sporting its own vibe and lifestyle advantages, it can be downright difficult to settle on where to look for a furnished apartment in London . Whether you’re a digital nomad looking for a studio apartment in London or just seeking a month to month rental in London, Blueground has you covered.",
    summary: [
      "1 bedroom",
      "1 bath",
      "WiFi",
      "City view",
      "3rd floor",
      "Elevator",
      "Parking",
    ],
    galleryImages: [
      "/images/Accommodation/property2.1.jpg",
      "/images/Accommodation/property2.2.jpg",
    ],
    amenities: [
      { name: "TV", icon: "bi-tv", note: "Flatscreen TV" },
      { name: "Fireplace", icon: "bi-fire" },
      { name: "Phone", icon: "bi-telephone" },
      { name: "Work desk", icon: "bi-laptop", note: "With computer" },
      { name: "Fridge", icon: "bi-box" },
      { name: "Kettle", icon: "bi-cup" },
      { name: "Coffee machine", icon: "bi-cup-hot" },
      { name: "Dishes", icon: "bi-egg-fried" },
      { name: "Washing machine", icon: "bi-droplet" },
      { name: "Dryer", icon: "bi-wind" },
      { name: "Iron", icon: "bi-lightning-charge" },
      { name: "Wardrobe", icon: "bi-door-closed" },
    ],
    mapPosition: [51.505, -0.13],
  },
  {
    id: 2,
    title: "Rhoncus suspendisse penatibus mauris, sit non",
    image: "/images/Accommodation/room3.png",
    roomDetails:
      "1 bedroom | 1 bath | WiFi | City view | 3rd floor | Elevator | Parking",
    available: "28 Nov 2021",
    price: 3490,
    description:
      "A truly global city, London has long been considered a cutting-edge metropolis and hub for culture, style and finance. With each borough, Tube zone and neighborhood of London sporting its own vibe and lifestyle advantages, it can be downright difficult to settle on where to look for a furnished apartment in London . Whether you’re a digital nomad looking for a studio apartment in London or just seeking a month to month rental in London, Blueground has you covered.",
    summary: [
      "1 bedroom",
      "1 bath",
      "WiFi",
      "City view",
      "3rd floor",
      "Elevator",
      "Parking",
    ],
    galleryImages: [
      "/images/Accommodation/property3.1.jpg",
      "/images/Accommodation/property3.2.jpg",
    ],
    amenities: [
      { name: "TV", icon: "bi-tv", note: "Flatscreen TV" },
      { name: "Fireplace", icon: "bi-fire" },
      { name: "Phone", icon: "bi-telephone" },
      { name: "Work desk", icon: "bi-laptop", note: "With computer" },
      { name: "Fridge", icon: "bi-box" },
      { name: "Kettle", icon: "bi-cup" },
      { name: "Coffee machine", icon: "bi-cup-hot" },
      { name: "Dishes", icon: "bi-egg-fried" },
      { name: "Washing machine", icon: "bi-droplet" },
      { name: "Dryer", icon: "bi-wind" },
      { name: "Iron", icon: "bi-lightning-charge" },
      { name: "Wardrobe", icon: "bi-door-closed" },
    ],
    mapPosition: [52.727, -1.1],
  },
  {
    id: 4,
    title: "Rhoncus suspendisse penatibus mauris, sit non",
    image: "/images/Accommodation/room2.png",
    roomDetails:
      "1 bedroom | 1 bath | WiFi | City view | 3rd floor | Elevator | Parking",
    available: "28 Nov 2021",
    price: 3490,
    description:
      "A truly global city, London has long been considered a cutting-edge metropolis and hub for culture, style and finance. With each borough, Tube zone and neighborhood of London sporting its own vibe and lifestyle advantages, it can be downright difficult to settle on where to look for a furnished apartment in London . Whether you’re a digital nomad looking for a studio apartment in London or just seeking a month to month rental in London, Blueground has you covered.",
    summary: [
      "1 bedroom",
      "1 bath",
      "WiFi",
      "City view",
      "3rd floor",
      "Elevator",
      "Parking",
    ],
    galleryImages: [
      "/images/Accommodation/property4.1.jpg",
      "/images/Accommodation/property4.2.jpg",
    ],
    amenities: [
      { name: "TV", icon: "bi-tv", note: "Flatscreen TV" },
      { name: "Fireplace", icon: "bi-fire" },
      { name: "Phone", icon: "bi-telephone" },
      { name: "Work desk", icon: "bi-laptop", note: "With computer" },
      { name: "Fridge", icon: "bi-box" },
      { name: "Kettle", icon: "bi-cup" },
      { name: "Coffee machine", icon: "bi-cup-hot" },
      { name: "Dishes", icon: "bi-egg-fried" },
      { name: "Washing machine", icon: "bi-droplet" },
      { name: "Dryer", icon: "bi-wind" },
      { name: "Iron", icon: "bi-lightning-charge" },
      { name: "Wardrobe", icon: "bi-door-closed" },
    ],
    mapPosition: [55.51, -2.12],
  },
  {
    id: 5,
    title: "Rhoncus suspendisse penatibus mauris, sit non",
    image: "/images/Accommodation/room1.png",
    roomDetails:
      "1 bedroom | 1 bath | WiFi | City view | 3rd floor | Elevator | Parking",
    available: "28 Nov 2021",
    price: 3490,
    description:
      "A truly global city, London has long been considered a cutting-edge metropolis and hub for culture, style and finance. With each borough, Tube zone and neighborhood of London sporting its own vibe and lifestyle advantages, it can be downright difficult to settle on where to look for a furnished apartment in London . Whether you’re a digital nomad looking for a studio apartment in London or just seeking a month to month rental in London, Blueground has you covered.",
    summary: [
      "1 bedroom",
      "1 bath",
      "WiFi",
      "City view",
      "3rd floor",
      "Elevator",
      "Parking",
    ],
    galleryImages: [
      "/images/Accommodation/property1.1.jpg",
      "/images/Accommodation/property1.2.jpg",
    ],
    amenities: [
      { name: "TV", icon: "bi-tv", note: "Flatscreen TV" },
      { name: "Fireplace", icon: "bi-fire" },
      { name: "Phone", icon: "bi-telephone" },
      { name: "Work desk", icon: "bi-laptop", note: "With computer" },
      { name: "Fridge", icon: "bi-box" },
      { name: "Kettle", icon: "bi-cup" },
      { name: "Coffee machine", icon: "bi-cup-hot" },
      { name: "Dishes", icon: "bi-egg-fried" },
      { name: "Washing machine", icon: "bi-droplet" },
      { name: "Dryer", icon: "bi-wind" },
      { name: "Iron", icon: "bi-lightning-charge" },
      { name: "Wardrobe", icon: "bi-door-closed" },
    ],
    mapPosition: [56.51, -3.43],
  },
  {
    id: 6,
    title: "Rhoncus suspendisse penatibus mauris, sit non",
    image: "/images/Accommodation/room0.png",
    roomDetails:
      "2 bedroom | 2 bath | WiFi | City view | 4th floor | Elevator | Parking",
    available: "28 Nov 2021",
    price: 3990,
    description:
      "A truly global city, London has long been considered a cutting-edge metropolis and hub for culture, style and finance. With each borough, Tube zone and neighborhood of London sporting its own vibe and lifestyle advantages, it can be downright difficult to settle on where to look for a furnished apartment in London . Whether you’re a digital nomad looking for a studio apartment in London or just seeking a month to month rental in London, Blueground has you covered.",
    summary: [
      "1 bedroom",
      "1 bath",
      "WiFi",
      "City view",
      "3rd floor",
      "Elevator",
      "Parking",
    ],
    galleryImages: [
      "/images/Accommodation/property3.1.jpg",
      "/images/Accommodation/property3.2.jpg",
    ],
    amenities: [
      { name: "TV", icon: "bi-tv", note: "Flatscreen TV" },
      { name: "Fireplace", icon: "bi-fire" },
      { name: "Phone", icon: "bi-telephone" },
      { name: "Work desk", icon: "bi-laptop", note: "With computer" },
      { name: "Fridge", icon: "bi-box" },
      { name: "Kettle", icon: "bi-cup" },
      { name: "Coffee machine", icon: "bi-cup-hot" },
      { name: "Dishes", icon: "bi-egg-fried" },
      { name: "Washing machine", icon: "bi-droplet" },
      { name: "Dryer", icon: "bi-wind" },
      { name: "Iron", icon: "bi-lightning-charge" },
      { name: "Wardrobe", icon: "bi-door-closed" },
    ],
    mapPosition: [55.21, -4.8],
  },
  {
    id: 7,
    title: "Rhoncus suspendisse penatibus mauris, sit non",
    image: "/images/Accommodation/room3.png",
    roomDetails:
      "1 bedroom | 1 bath | WiFi | City view | 3rd floor | Elevator | Parking",
    available: "28 Nov 2021",
    price: 3490,
    description:
      "A truly global city, London has long been considered a cutting-edge metropolis and hub for culture, style and finance. With each borough, Tube zone and neighborhood of London sporting its own vibe and lifestyle advantages, it can be downright difficult to settle on where to look for a furnished apartment in London . Whether you’re a digital nomad looking for a studio apartment in London or just seeking a month to month rental in London, Blueground has you covered.",
    summary: [
      "1 bedroom",
      "1 bath",
      "WiFi",
      "City view",
      "3rd floor",
      "Elevator",
      "Parking",
    ],
    galleryImages: [
      "/images/Accommodation/property1.1.jpg",
      "/images/Accommodation/property1.2.jpg",
    ],
    amenities: [
      { name: "TV", icon: "bi-tv", note: "Flatscreen TV" },
      { name: "Fireplace", icon: "bi-fire" },
      { name: "Phone", icon: "bi-telephone" },
      { name: "Work desk", icon: "bi-laptop", note: "With computer" },
      { name: "Fridge", icon: "bi-box" },
      { name: "Kettle", icon: "bi-cup" },
      { name: "Coffee machine", icon: "bi-cup-hot" },
      { name: "Dishes", icon: "bi-egg-fried" },
      { name: "Washing machine", icon: "bi-droplet" },
      { name: "Dryer", icon: "bi-wind" },
      { name: "Iron", icon: "bi-lightning-charge" },
      { name: "Wardrobe", icon: "bi-door-closed" },
    ],
    mapPosition: [53.51, -2.53],
  },
  {
    id: 8,
    title: "Rhoncus suspendisse penatibus mauris, sit non",
    image: "/images/Accommodation/room2.png",
    roomDetails:
      "1 bedroom | 1 bath | WiFi | City view | 3rd floor | Elevator | Parking",
    available: "28 Nov 2021",
    price: 3490,
    description:
      "A truly global city, London has long been considered a cutting-edge metropolis and hub for culture, style and finance. With each borough, Tube zone and neighborhood of London sporting its own vibe and lifestyle advantages, it can be downright difficult to settle on where to look for a furnished apartment in London . Whether you’re a digital nomad looking for a studio apartment in London or just seeking a month to month rental in London, Blueground has you covered.",
    summary: [
      "1 bedroom",
      "1 bath",
      "WiFi",
      "City view",
      "3rd floor",
      "Elevator",
      "Parking",
    ],
    galleryImages: [
      "/images/RAccommodation/property2.1.jpg",
      "/images/Accommodation/property2.2.jpg",
    ],
    amenities: [
      { name: "TV", icon: "bi-tv", note: "Flatscreen TV" },
      { name: "Fireplace", icon: "bi-fire" },
      { name: "Phone", icon: "bi-telephone" },
      { name: "Work desk", icon: "bi-laptop", note: "With computer" },
      { name: "Fridge", icon: "bi-box" },
      { name: "Kettle", icon: "bi-cup" },
      { name: "Coffee machine", icon: "bi-cup-hot" },
      { name: "Dishes", icon: "bi-egg-fried" },
      { name: "Washing machine", icon: "bi-droplet" },
      { name: "Dryer", icon: "bi-wind" },
      { name: "Iron", icon: "bi-lightning-charge" },
      { name: "Wardrobe", icon: "bi-door-closed" },
    ],
    mapPosition: [55.51, -4.43],
  },
  {
    id: 9,
    title: "Rhoncus suspendisse penatibus mauris, sit non",
    image: "/images/Accommodation/room1.png",
    roomDetails:
      "1 bedroom | 1 bath | WiFi | City view | 3rd floor | Elevator | Parking",
    available: "28 Nov 2021",
    price: 3490,
    description:
      "A truly global city, London has long been considered a cutting-edge metropolis and hub for culture, style and finance. With each borough, Tube zone and neighborhood of London sporting its own vibe and lifestyle advantages, it can be downright difficult to settle on where to look for a furnished apartment in London . Whether you’re a digital nomad looking for a studio apartment in London or just seeking a month to month rental in London, Blueground has you covered.",
    summary: [
      "1 bedroom",
      "1 bath",
      "WiFi",
      "City view",
      "3rd floor",
      "Elevator",
      "Parking",
    ],
    galleryImages: [
      "/images/Accommodation/property3.1.jpg",
      "/images/Accommodation/property3.2.jpg",
    ],
    amenities: [
      { name: "TV", icon: "bi-tv", note: "Flatscreen TV" },
      { name: "Fireplace", icon: "bi-fire" },
      { name: "Phone", icon: "bi-telephone" },
      { name: "Work desk", icon: "bi-laptop", note: "With computer" },
      { name: "Fridge", icon: "bi-box" },
      { name: "Kettle", icon: "bi-cup" },
      { name: "Coffee machine", icon: "bi-cup-hot" },
      { name: "Dishes", icon: "bi-egg-fried" },
      { name: "Washing machine", icon: "bi-droplet" },
      { name: "Dryer", icon: "bi-wind" },
      { name: "Iron", icon: "bi-lightning-charge" },
      { name: "Wardrobe", icon: "bi-door-closed" },
    ],
    mapPosition: [55.51, -2.32],
  },
  {
    id: 10,
    title: "Rhoncus suspendisse penatibus mauris, sit non",
    image: "/images/Accommodation/room0.png",
    roomDetails:
      "1 bedroom | 1 bath | WiFi | City view | 3rd floor | Elevator | Parking",
    available: "28 Nov 2021",
    price: 3490,
    description:
      "A truly global city, London has long been considered a cutting-edge metropolis and hub for culture, style and finance. With each borough, Tube zone and neighborhood of London sporting its own vibe and lifestyle advantages, it can be downright difficult to settle on where to look for a furnished apartment in London . Whether you’re a digital nomad looking for a studio apartment in London or just seeking a month to month rental in London, Blueground has you covered.",
    summary: [
      "1 bedroom",
      "1 bath",
      "WiFi",
      "City view",
      "3rd floor",
      "Elevator",
      "Parking",
    ],
    galleryImages: [
      "/images/Accommodation/property4.1.jpg",
      "/images/Accommodation/property4.2.jpg",
    ],
    amenities: [
      { name: "TV", icon: "bi-tv", note: "Flatscreen TV" },
      { name: "Fireplace", icon: "bi-fire" },
      { name: "Phone", icon: "bi-telephone" },
      { name: "Work desk", icon: "bi-laptop", note: "With computer" },
      { name: "Fridge", icon: "bi-box" },
      { name: "Kettle", icon: "bi-cup" },
      { name: "Coffee machine", icon: "bi-cup-hot" },
      { name: "Dishes", icon: "bi-egg-fried" },
      { name: "Washing machine", icon: "bi-droplet" },
      { name: "Dryer", icon: "bi-wind" },
      { name: "Iron", icon: "bi-lightning-charge" },
      { name: "Wardrobe", icon: "bi-door-closed" },
    ],
    mapPosition: [52.51, -0.12],
  },
];
